version: '3.8'
services:
  exercises:
    profiles: ["exercises"] # exclude from "docker-compose up"
    build: .
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    environment:
      SERVER_URL: https://train.skillerwhale.com
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: ".py"
      IGNORE_DIRS: ".git"
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
